ALTER TABLE EMS_REDIR_PETICIO MOVE LOB (ERROR) STORE AS EMS_REDIRPET_ERROR_LOB (TABLESPACE EMISERV_LOB);
ALTER TABLE EMS_REDIR_SOLICITUD MOVE LOB (ERROR) STORE AS EMS_REDIRSOL_ERROR_LOB (TABLESPACE EMISERV_LOB);
ALTER TABLE EMS_REDIR_MISSATGE MOVE LOB (XML) STORE AS EMS_REDIRMIS_XML_LOB (TABLESPACE EMISERV_LOB);
ALTER TABLE EMS_BACKOFFICE_COM MOVE LOB (PETICIO_XML) STORE AS EMS_BACKCOM_PETICIO_LOB (TABLESPACE EMISERV_LOB);
ALTER TABLE EMS_BACKOFFICE_COM MOVE LOB (RESPOSTA_XML) STORE AS EMS_BACKCOM_RESPOSTA_LOB (TABLESPACE EMISERV_LOB);

