ALTER TABLE EMS_SERVEI ADD (
  PRIMARY KEY (ID),
  UNIQUE (CODI));

ALTER TABLE EMS_USUARI ADD (
  PRIMARY KEY (CODI),
  UNIQUE (NIF));

ALTER TABLE EMS_SERVEI ADD (
  CONSTRAINT EMS_USUCRE_SERVEI_FK FOREIGN KEY (CREATEDBY_CODI) 
    REFERENCES EMS_USUARI (CODI),
  CONSTRAINT EMS_USUMOD_SERVEI_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) 
    REFERENCES EMS_USUARI (CODI));

ALTER TABLE EMS_ACL_CLASS ADD (
  CONSTRAINT EMS_ACL_CLASS_PK PRIMARY KEY (ID),
  CONSTRAINT EMS_ACL_CLASS_CLASS_UK UNIQUE (CLASS));

ALTER TABLE EMS_ACL_ENTRY ADD (
  CONSTRAINT EMS_ACL_ENTRY_PK PRIMARY KEY (ID),
  CONSTRAINT EMS_ACL_ENTRY_IDENT_ORDER_UK UNIQUE (ACL_OBJECT_IDENTITY, ACE_ORDER));

ALTER TABLE EMS_ACL_OBJECT_IDENTITY ADD (
  CONSTRAINT EMS_ACL_OID_PK PRIMARY KEY (ID),
  CONSTRAINT EMS_ACL_IOD_CLASS_IDENTITY_UK UNIQUE (OBJECT_ID_CLASS, OBJECT_ID_IDENTITY));

ALTER TABLE EMS_ACL_SID ADD (
  CONSTRAINT EMS_ACL_SID_PK PRIMARY KEY (ID),
  CONSTRAINT EMS_ACL_SID_PRINCIPAL_SID_UK UNIQUE (SID, PRINCIPAL));


ALTER TABLE EMS_ACL_ENTRY ADD CONSTRAINT EMS_ACL_ENTRY_GRANTING_CK
  CHECK (GRANTING in (1,0));

ALTER TABLE EMS_ACL_ENTRY ADD CONSTRAINT EMS_ACL_ENTRY_AUDIT_SUCCESS_CK
  CHECK (AUDIT_SUCCESS in (1,0));

ALTER TABLE EMS_ACL_ENTRY ADD CONSTRAINT EMS_ACL_ENTRY_AUDIT_FAILURE_CK
  CHECK (AUDIT_FAILURE in (1,0));

ALTER TABLE EMS_ACL_OBJECT_IDENTITY ADD CONSTRAINT EMS_ACL_OID_ENTRIES_CK
  CHECK (ENTRIES_INHERITING in (1,0));

ALTER TABLE EMS_ACL_SID ADD CONSTRAINT EMS_ACL_SID_PRINCIPAL_CK
  CHECK (PRINCIPAL in (1,0));


ALTER TABLE EMS_ACL_ENTRY ADD CONSTRAINT EMS_ACL_OID_ENTRY_FK
  FOREIGN KEY (ACL_OBJECT_IDENTITY)
  REFERENCES EMS_ACL_OBJECT_IDENTITY (ID);

ALTER TABLE EMS_ACL_ENTRY ADD CONSTRAINT EMS_ACL_SID_ENTRY_FK
  FOREIGN KEY (SID)
  REFERENCES EMS_ACL_SID (ID);

ALTER TABLE EMS_ACL_OBJECT_IDENTITY ADD CONSTRAINT EMS_ACL_CLASS_OID_FK
  FOREIGN KEY (OBJECT_ID_CLASS)
  REFERENCES EMS_ACL_CLASS (ID);

ALTER TABLE EMS_ACL_OBJECT_IDENTITY ADD CONSTRAINT EMS_ACL_PARENT_OID_FK
  FOREIGN KEY (PARENT_OBJECT)
  REFERENCES EMS_ACL_OBJECT_IDENTITY (ID);

ALTER TABLE EMS_ACL_OBJECT_IDENTITY ADD CONSTRAINT EMS_ACL_SID_OID_FK
  FOREIGN KEY (OWNER_SID)
  REFERENCES EMS_ACL_SID (ID);
