GRANT SELECT, UPDATE, INSERT, DELETE ON EMS_USUARI TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON EMS_SERVEI TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON EMS_ACL_CLASS TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON EMS_ACL_ENTRY TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON EMS_ACL_OBJECT_IDENTITY TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON EMS_ACL_SID TO WWW_EMISERV;

GRANT SELECT ON EMS_ACL_SID_SEQ TO WWW_EMISERV;
GRANT SELECT ON EMS_ACL_CLASS_SEQ TO WWW_EMISERV;
GRANT SELECT ON EMS_ACL_OBJECT_IDENTITY_SEQ TO WWW_EMISERV;
GRANT SELECT ON EMS_ACL_ENTRY_SEQ TO WWW_EMISERV;

GRANT SELECT ON HIBERNATE_SEQUENCE TO WWW_EMISERV;
