CREATE OR REPLACE TRIGGER ems_acl_sid_idgen BEFORE INSERT ON ems_acl_sid FOR EACH ROW BEGIN SELECT ems_acl_sid_seq.NEXTVAL INTO :NEW.ID FROM DUAL;

END;

CREATE OR REPLACE TRIGGER ems_acl_class_idgen BEFORE INSERT ON ems_acl_class FOR EACH ROW BEGIN SELECT ems_acl_class_seq.NEXTVAL INTO :NEW.ID FROM DUAL;

END;

CREATE OR REPLACE TRIGGER ems_acl_oid_idgen BEFORE INSERT ON ems_acl_object_identity FOR EACH ROW BEGIN SELECT ems_acl_oid_seq.NEXTVAL INTO :NEW.ID FROM DUAL;

END;

CREATE OR REPLACE TRIGGER ems_acl_entry_idgen BEFORE INSERT ON ems_acl_entry FOR EACH ROW BEGIN SELECT ems_acl_entry_seq.NEXTVAL INTO :NEW.ID FROM DUAL;

END;