CREATE OR REPLACE TRIGGER EMS_ACLCLA_IDGEN
BEFORE INSERT ON EMS_ACL_CLASS
FOR EACH ROW
  BEGIN
    SELECT EMS_ACL_CLASS_SEQ.NEXTVAL INTO :new.id FROM dual;
  END;
 
CREATE OR REPLACE TRIGGER EMS_ACLENT_IDGEN
BEFORE INSERT ON EMS_ACL_ENTRY
FOR EACH ROW
  BEGIN
    SELECT EMS_ACL_ENTRY_SEQ.NEXTVAL INTO :new.id FROM dual;
  END;
 
CREATE OR REPLACE TRIGGER EMS_ACLOID_IDGEN
BEFORE INSERT ON EMS_ACL_OBJECT_IDENTITY
FOR EACH ROW
  BEGIN
    SELECT EMS_ACL_OBJECT_IDENTITY_SEQ.NEXTVAL INTO :new.id FROM dual;
  END;
 
CREATE OR REPLACE TRIGGER EMS_ACLSID_IDGEN
BEFORE INSERT ON EMS_ACL_SID
FOR EACH ROW
  BEGIN
    SELECT EMS_ACL_SID_SEQ.NEXTVAL INTO :new.id FROM dual;
  END;