GRANT SELECT, UPDATE, INSERT, DELETE ON ems_backoffice_com TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON ems_backoffice_pet TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON ems_backoffice_sol_RUTA_DESTI TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON ems_redir_missatge TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON ems_redir_peticio TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON ems_redir_solicitud TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON ems_servei TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON ems_servei_ruta_desti TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON ems_usuari TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON ems_acl_sid TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON ems_acl_class TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON ems_acl_object_identity TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON ems_acl_entry TO WWW_EMISERV;

GRANT SELECT ON ems_acl_sid_seq TO WWW_EMISERV;
GRANT SELECT ON ems_acl_class_seq TO WWW_EMISERV;
GRANT SELECT ON ems_acl_oid_seq TO WWW_EMISERV;
GRANT SELECT ON ems_acl_entry_seq TO WWW_EMISERV;

GRANT SELECT ON hibernate_sequence TO WWW_EMISERV;
