UPDATE CORE_PARAMETRO_CONFIGURACION SET VALOR='4.0.0' WHERE NOMBRE='version.datamodel.scsp';

commit;
RENAME SCSP_CODIGO_ERROR TO CORE_CODIGO_ERROR; 
RENAME ORGANISMO_CESIONARIO TO CORE_ORGANISMO_CESIONARIO;
RENAME SCSP_ESTADO_PETICION TO CORE_ESTADO_PETICION;
RENAME SCSP_CODIGO_ERROR_SECUNDARIO TO CORE_EM_CODIGO_ERROR_SECUN;
RENAME AUTORIZACION_APLICACION TO CORE_EM_APLICACION;
RENAME AUTORIZACION_CA TO CORE_EM_AUTORIZACION_CA;
RENAME AUTORIZACION_CERTIFICADO TO CORE_EM_AUTORIZACION_CERT;
RENAME AUTORIZACION_ORGANISMO TO CORE_EM_AUTORIZACION_ORGANISMO;
RENAME EMISOR_BACKOFFICE TO CORE_EM_BACKOFFICE;
RENAME SCSP_SECUENCIA_IDTRANSMISION TO CORE_EM_SECUENCIA_IDTRANS;
COMMIT;
ALTER TABLE    CORE_EM_SECUENCIA_IDTRANS MODIFY    (  PREFIJO  varchar2(9)  );
ALTER TABLE    CORE_SERVICIO MODIFY    (  PREFIJOPETICION  VARCHAR2(9)  );
ALTER TABLE    CORE_SERVICIO MODIFY    (  PREFIJOIDTRANSMISION  VARCHAR2(9)  ); 
COMMIT;
DROP PROCEDURE GETSECUENCIAIDTRANSMISION;
COMMIT;
CREATE OR REPLACE PROCEDURE "GETSECUENCIAIDTRANSMISION"  (  prefijo_param in varchar2, on_Secuencial out number)as  rRegistro ROWID;

begin  
    select ROWID, SECUENCIA+1 into rRegistro, on_Secuencial from CORE_EM_SECUENCIA_IDTRANS where PREFIJO = prefijo_param for update;
    update CORE_EM_SECUENCIA_IDTRANS set SECUENCIA = on_Secuencial, FECHAGENERACION=sysdate where rowid = rRegistro;  
	commit; 
    exception when no_data_found then on_Secuencial := 1;    
    insert into CORE_EM_SECUENCIA_IDTRANS (PREFIJO, SECUENCIA,FECHAGENERACION) values (prefijo_param, on_Secuencial,(SELECT SYSDATE FROM DUAL)); 
commit; 
end;
/

--ALTER TABLE CORE_EM_CODIGO_ERROR_SECUN MODIFY (DESCRIPCION CLOB);
--ALTER TABLE CORE_LOG MODIFY (MENSAJE CLOB );
ALTER TABLE CORE_ORGANISMO_CESIONARIO MODIFY ( LOGO BLOB ); 
--ALTER TABLE CORE_TOKEN_DATA MODIFY ( DATOS CLOB ); 
--ALTER TABLE CORE_TRANSMISION MODIFY ( XMLTRANSMISION CLOB );

COMMIT;
DECLARE
    cursor cnombre Is select index_name from user_indexes where status='UNUSABLE';
BEGIN 
    FOR rNOMBRE IN cnombre LOOP 
		execute immediate 'ALTER INDEX ' || rNOMBRE.index_name || ' REBUILD ';
    END LOOP;
	COMMIT;
END;
/

ALTER TABLE CORE_EM_AUTORIZACION_ORGANISMO DROP COLUMN IDAPLICACION CASCADE CONSTRAINTS;

update core_em_autorizacion_cert ac set idcertificado = (select s.id from core_servicio s where s.codcertificado = ac.codcertificado);
alter table core_em_autorizacion_cert drop primary key;
alter table core_em_autorizacion_cert drop column codcertificado;
alter table core_em_autorizacion_cert add primary key (idcertificado, idaplicacion, idorganismo);
alter table core_em_autorizacion_cert add constraint autorizacion_cert_servicio foreign key (idcertificado) references core_servicio (id) enable novalidate;

alter table core_em_autorizacion_cert modify fechaalta null;

ALTER TABLE EMS_SERVEI ADD XSD_ACTIVA NUMBER(1);
ALTER TABLE EMS_SERVEI ADD XSD_ESQUEMA_BAK VARCHAR2(256);

/* 4.0.0 a 4.2.0*/
ALTER TABLE CORE_EM_APLICACION DROP CONSTRAINT APLI_CODCA;
commit;
UPDATE CORE_PARAMETRO_CONFIGURACION SET VALOR='4.2.0' where NOMBRE='version.datamodel.scsp';  
ALTER TABLE CORE_EM_AUTORIZACION_CA DROP PRIMARY KEY DROP INDEX;
ALTER TABLE CORE_EM_AUTORIZACION_CA ADD ID NUMBER(19,0); 
COMMIT;
CREATE SEQUENCE ID_AUTORIZACION_CA_SEQ START WITH     1 INCREMENT BY   1 NOCACHE NOCYCLE;
COMMIT;
UPDATE CORE_EM_AUTORIZACION_CA  SET ID=ID_AUTORIZACION_CA_SEQ.NEXTVAL;
COMMIT;
ALTER TABLE CORE_EM_AUTORIZACION_CA ADD CONSTRAINT CORE_EM_AUTORIZACION_CA_PK PRIMARY KEY (ID);
COMMIT; 
ALTER TABLE CORE_EM_APLICACION ADD AUTORIDADCERTIF2 NUMBER(19,0);  
UPDATE CORE_EM_APLICACION AP
   SET (AP.AUTORIDADCERTIF2) = (SELECT CA.ID
                         FROM CORE_EM_AUTORIZACION_CA CA
                        WHERE CA.CODCA = AP.AUTORIDADCERTIF);
commit;
ALTER TABLE CORE_EM_APLICACION DROP COLUMN AUTORIDADCERTIF;
COMMIT; 
ALTER TABLE CORE_EM_APLICACION RENAME COLUMN AUTORIDADCERTIF2 TO AUTORIDADCERTIF;
COMMIT;
ALTER TABLE CORE_EM_APLICACION MODIFY (AUTORIDADCERTIF NOT NULL);
COMMIT;
ALTER TABLE CORE_EM_APLICACION ADD CONSTRAINT APLI_CODCA FOREIGN KEY (AUTORIDADCERTIF) REFERENCES CORE_EM_AUTORIZACION_CA(ID);

/* 4.2.0 a 4.3.0*/
UPDATE CORE_PARAMETRO_CONFIGURACION SET VALOR='4.3.0' WHERE NOMBRE='version.datamodel.scsp'; 
ALTER TABLE    CORE_TRANSMISION MODIFY DOCTITULAR  VARCHAR2(30);
ALTER TABLE    CORE_TRANSMISION MODIFY EXPEDIENTE  VARCHAR2(65);
ALTER TABLE    CORE_EM_CODIGO_ERROR_SECUN MODIFY CODIGOSECUNDARIO  VARCHAR2(16); 
ALTER TABLE CORE_TRANSMISION ADD   ESTADOSECUNDARIO VARCHAR2(16); 
ALTER TABLE CORE_TRANSMISION ADD   CODIGOUNIDADTRAMITADORA VARCHAR2(9); 
ALTER TABLE CORE_TRANSMISION ADD   SEUDONIMOFUNCIONARIO VARCHAR2(32); 
ALTER TABLE CORE_PETICION_RESPUESTA ADD   ERRORSECUNDARIO VARCHAR2(1024); 
ALTER TABLE CORE_PETICION_RESPUESTA ADD   ESTADOSECUNDARIO VARCHAR2(16); 
ALTER TABLE CORE_SERVICIO ADD   XPATHCODIGOERRORSECUNDARIO VARCHAR2(256); 
INSERT INTO CORE_CODIGO_ERROR(CODIGO,DESCRIPCION) VALUES ('0317','El organismo solicitante {0} de la solicitud de respuesta no coincide con el enviado en la petición');

/* 4.3.0 a 4.4.0*/
DELETE  FROM CORE_PARAMETRO_CONFIGURACION WHERE NOMBRE='core_log.enabled';
UPDATE CORE_PARAMETRO_CONFIGURACION SET VALOR='4.4.0' WHERE NOMBRE='version.datamodel.scsp'; 
ALTER TABLE CORE_PETICION_RESPUESTA ADD ERROR2 VARCHAR2 (4000);
ALTER TABLE CORE_TRANSMISION ADD ERROR2 VARCHAR2 (4000);
commit;
DECLARE
   CURSOR c1 is
      SELECT error,idpeticion   FROM core_peticion_respuesta  ; 
var_var  VARCHAR2(4000);
long_var LONG;
sql_stmt0 VARCHAR2(4000);
sql_stmt VARCHAR2(4000);
sql_stmt2 VARCHAR2(4000);
sql_stmt3 VARCHAR2(4000);
BEGIN   
 sql_stmt2 := 'ALTER TABLE   core_peticion_respuesta DROP COLUMN error';
 sql_stmt3 := 'ALTER TABLE core_peticion_respuesta   RENAME COLUMN error2 TO error';
   FOR peticion_rec in c1
   LOOP
      update core_peticion_respuesta set error2= substr(peticion_rec.error,1,4000) where idpeticion=peticion_rec.idpeticion;
   END LOOP;  
  EXECUTE IMMEDIATE sql_stmt2 ; 
  EXECUTE IMMEDIATE sql_stmt3 ;  
END;
/

DECLARE
   CURSOR c1 is
      SELECT ERROR,IDPETICION,IDTRANSMISION  FROM CORE_TRANSMISION  ; 
		var_var  VARCHAR2(4000);
		long_var LONG;
		sql_stmt0 VARCHAR2(4000);
		sql_stmt VARCHAR2(4000);
		sql_stmt2 VARCHAR2(4000);
		sql_stmt3 VARCHAR2(4000);
		BEGIN   
		 sql_stmt2 := 'ALTER TABLE   CORE_TRANSMISION DROP COLUMN error';
		 sql_stmt3 := 'ALTER TABLE CORE_TRANSMISION   RENAME COLUMN error2 TO error';
		   FOR TRANSMISION_REC in c1
		   LOOP
		      UPDATE CORE_TRANSMISION SET ERROR2= SUBSTR(TRANSMISION_REC.ERROR,1,4000) WHERE IDPETICION=TRANSMISION_REC.IDPETICION AND IDTRANSMISION=TRANSMISION_REC.IDTRANSMISION;
		   END LOOP;  
		  EXECUTE IMMEDIATE sql_stmt2 ; 
		  EXECUTE IMMEDIATE sql_stmt3 ;  
		END;
/

/* 4.4.0 a 4.5.0*/
UPDATE CORE_PARAMETRO_CONFIGURACION SET VALOR='4.5.0' WHERE NOMBRE='version.datamodel.scsp';
ALTER TABLE CORE_EM_APLICACION ADD DESCRIPCION VARCHAR2(512) NULL ;

/* 4.5.0 a 4.6.0*/
ALTER TABLE CORE_ORGANISMO_CESIONARIO ADD CODIGOUNIDADTRAMITADORA VARCHAR(9);

