ALTER TABLE CORE_BLOQUEO ADD(
	CONSTRAINT CORE_BLOQUEO_PK PRIMARY KEY(IDBLOQUEO)
);

ALTER TABLE CORE_CACHE_CERTIFICADOS ADD(
	CONSTRAINT CORE_CACHE_CERTIFICADOS_PK PRIMARY KEY(NUMSERIE, AUTORIDADCERTIF)
);

ALTER TABLE CORE_ORGANISMO_CESIONARIO ADD(
	CONSTRAINT CORE_ORGANISMO_CESIONARIO_PK PRIMARY KEY(ID)
);

ALTER TABLE CORE_CLAVE_PRIVADA ADD(
	CONSTRAINT CORE_CLAVE_PRIVADA_PK PRIMARY KEY(ID),
	CONSTRAINT CLAVE_PRIVADA_ORG FOREIGN KEY (ORGANISMO) REFERENCES CORE_ORGANISMO_CESIONARIO (ID)
);

ALTER TABLE CORE_CLAVE_PUBLICA ADD(
	CONSTRAINT CORE_CLAVE_PUBLICA_PK PRIMARY KEY(ID)
);

ALTER TABLE CORE_CODIGO_ERROR ADD(
	CONSTRAINT CORE_CODIGO_ERROR_PK PRIMARY KEY(CODIGO)
);

ALTER TABLE CORE_EMISOR_CERTIFICADO ADD(
	CONSTRAINT CORE_EMISOR_CERTIFICADO_PK PRIMARY KEY(ID)
);

ALTER TABLE CORE_EM_AUTORIZACION_CA ADD(
	CONSTRAINT CORE_EM_AUTORIZACION_CA_PK PRIMARY KEY(CODCA)
);

ALTER TABLE CORE_EM_APLICACION ADD(
	CONSTRAINT CORE_EM_APLICACION_PK PRIMARY KEY(IDAPLICACION)
);

ALTER TABLE CORE_SERVICIO ADD(
	CONSTRAINT CORE_SERVICIO_PK PRIMARY KEY(ID),
	CONSTRAINT SERV_EMISOR FOREIGN KEY (EMISOR) REFERENCES CORE_EMISOR_CERTIFICADO (ID),
	CONSTRAINT SERV_CLAVEFIRMA FOREIGN KEY (CLAVEFIRMA) REFERENCES CORE_CLAVE_PRIVADA (ID),
	CONSTRAINT SERV_CLAVECIFRADO FOREIGN KEY (CLAVECIFRADO) REFERENCES CORE_CLAVE_PUBLICA (ID)
);

ALTER TABLE CORE_EM_AUTORIZACION_ORGANISMO ADD(
	CONSTRAINT CORE_EM_AUTORIZACION_ORG_PK PRIMARY KEY(ID)
);

ALTER TABLE CORE_EM_AUTORIZACION_CERT ADD(
	CONSTRAINT CORE_EM_AUTORIZACION_CERT_PK PRIMARY KEY(ID),
	CONSTRAINT UNIQUE_SERV_APL_ORG_BAJA UNIQUE (IDCERTIFICADO, IDAPLICACION, IDORGANISMO, FECHABAJA),
	CONSTRAINT AUT_CERT_APLICACION FOREIGN KEY (IDAPLICACION) REFERENCES CORE_EM_APLICACION (IDAPLICACION),
	CONSTRAINT AUT_CERT_ORGANISMO FOREIGN KEY (IDORGANISMO) REFERENCES CORE_EM_AUTORIZACION_ORGANISMO(ID)
);

ALTER TABLE CORE_EM_BACKOFFICE ADD(
	CONSTRAINT CORE_EM_BACKOFFICE_PK PRIMARY KEY(CERTIFICADO),
	CONSTRAINT EMISOR_BO_SERVICIO FOREIGN KEY (CERTIFICADO) REFERENCES CORE_SERVICIO (ID) NOVALIDATE
);

ALTER TABLE CORE_EM_CODIGO_ERROR_SECUN ADD(
	CONSTRAINT CORE_EM_CODIGO_ERROR_SECUN_PK PRIMARY KEY (CODIGOSECUNDARIO, CODIGO),
	CONSTRAINT FK693728FC26873B60 FOREIGN KEY (CODIGO) REFERENCES CORE_CODIGO_ERROR (CODIGO)
);

ALTER TABLE CORE_EM_SECUENCIA_IDTRANS ADD(
	CONSTRAINT CORE_EM_SECUENCIA_IDTRANS_PK PRIMARY KEY (PREFIJO)
);

ALTER TABLE CORE_ESTADO_PETICION ADD(
	CONSTRAINT CORE_ESTADO_PETICION_PK PRIMARY KEY (CODIGO)
);

ALTER TABLE CORE_LOG ADD(
	CONSTRAINT CORE_LOG_PK PRIMARY KEY (ID)
);

ALTER TABLE CORE_MODULO ADD(
	CONSTRAINT CORE_MODULO_PK PRIMARY KEY (NOMBRE)
);

ALTER TABLE CORE_MODULO_CONFIGURACION ADD(
	CONSTRAINT CORE_MODULO_CONFIGURACION_PK PRIMARY KEY (MODULO, CERTIFICADO),
	CONSTRAINT MOD_CONF_SERVICIO FOREIGN KEY (CERTIFICADO) REFERENCES CORE_SERVICIO (ID) NOVALIDATE
);

ALTER TABLE CORE_PARAMETRO_CONFIGURACION ADD(
	CONSTRAINT CORE_PARAMETRO_CONFIG_PK PRIMARY KEY (NOMBRE)
);

ALTER TABLE CORE_PETICION_RESPUESTA ADD(
	CONSTRAINT CORE_PETICION_RESPUESTA_PK PRIMARY KEY (IDPETICION),
	CONSTRAINT PET_RESP_SERVICIO FOREIGN KEY (CERTIFICADO) REFERENCES CORE_SERVICIO (ID) NOVALIDATE
);

ALTER TABLE CORE_SECUENCIA_IDPETICION ADD(
	CONSTRAINT CORE_SECUENCIA_IDPETICION_PK PRIMARY KEY (PREFIJO)
);

ALTER TABLE CORE_TIPO_MENSAJE ADD(
	CONSTRAINT CORE_TIPO_MENSAJE_PK PRIMARY KEY (TIPO)
);

ALTER TABLE CORE_TOKEN_DATA ADD(
	CONSTRAINT CORE_TOKEN_DATA_PK PRIMARY KEY (IDPETICION, TIPOMENSAJE),
	CONSTRAINT FK35573ED06007240E FOREIGN KEY (TIPOMENSAJE) REFERENCES CORE_TIPO_MENSAJE (TIPO),
	CONSTRAINT FK35573ED082700A73 FOREIGN KEY (IDPETICION) REFERENCES CORE_PETICION_RESPUESTA (IDPETICION)
);

ALTER TABLE CORE_TRANSMISION ADD(
	CONSTRAINT CORE_TRANSMISION_PK PRIMARY KEY (IDSOLICITUD, IDPETICION)
);

ALTER TABLE SCSP_CODIGO_ERROR ADD(
	CONSTRAINT SCSP_CODIGO_ERROR_PK PRIMARY KEY (CODIGO)
);

ALTER TABLE SCSP_SECUENCIA_IDTRANSMISION ADD(
	CONSTRAINT SCSP_SECUENCIA_IDTRANS_PK PRIMARY KEY (PREFIJO)
);

ALTER TABLE SCSP_CODIGO_ERROR_SECUNDARIO ADD(
	CONSTRAINT SCSP_COD_ERROR_SECUND_PK PRIMARY KEY (CODIGOSECUNDARIO, CODIGO),
	CONSTRAINT ERROR_SEC_ERRPR FOREIGN KEY (CODIGO) REFERENCES SCSP_CODIGO_ERROR (CODIGO) 
);

ALTER TABLE SCSP_ESTADO_PETICION ADD(
	CONSTRAINT SCSP_ESTADO_PETICION_PK PRIMARY KEY (CODIGO)
);

ALTER TABLE EMS_ACL_CLASS ADD(
	CONSTRAINT EMS_ACL_CLASS_PK PRIMARY KEY (ID),
	CONSTRAINT EMS_ACL_CLASS_CLASS_UK UNIQUE (CLASS)
);

ALTER TABLE EMS_ACL_SID ADD(
	CONSTRAINT EMS_ACL_SID_PK PRIMARY KEY (ID), 
	CONSTRAINT EMS_ACL_SID_PRINCIPAL_SID_UK UNIQUE (SID, PRINCIPAL), 
	CONSTRAINT EMS_ACL_SID_PRINCIPAL_CK CHECK (PRINCIPAL in (1,0))
);

ALTER TABLE EMS_ACL_OBJECT_IDENTITY ADD(
	CONSTRAINT EMS_ACL_OID_PK PRIMARY KEY (ID), 
	CONSTRAINT EMS_ACL_OID_ENTRIES_CK CHECK (ENTRIES_INHERITING in (1,0)), 
	CONSTRAINT EMS_ACL_CLASS_OID_FK FOREIGN KEY (OBJECT_ID_CLASS) REFERENCES EMS_ACL_CLASS (ID), 
	CONSTRAINT EMS_ACL_PARENT_OID_FK FOREIGN KEY (PARENT_OBJECT) REFERENCES EMS_ACL_OBJECT_IDENTITY (ID), 
	CONSTRAINT EMS_ACL_SID_OID_FK FOREIGN KEY (OWNER_SID) REFERENCES EMS_ACL_SID (ID) 
);

ALTER TABLE EMS_ACL_ENTRY ADD(
	 CONSTRAINT EMS_ACL_ENTRY_PK PRIMARY KEY (ID), 
	 CONSTRAINT EMS_ACL_ENTRY_IDENT_ORDER_UK UNIQUE (ACL_OBJECT_IDENTITY, ACE_ORDER), 
	 CONSTRAINT EMS_ACL_ENTRY_GRANTING_CK CHECK (GRANTING in (1,0)) , 
	 CONSTRAINT EMS_ACL_ENTRY_AUDIT_SUCCESS_CK CHECK (AUDIT_SUCCESS in (1,0)) , 
	 CONSTRAINT EMS_ACL_ENTRY_AUDIT_FAILURE_CK CHECK (AUDIT_FAILURE in (1,0)) , 
	 CONSTRAINT EMS_ACL_OID_ENTRY_FK FOREIGN KEY (ACL_OBJECT_IDENTITY) REFERENCES EMS_ACL_OBJECT_IDENTITY (ID) , 
	 CONSTRAINT EMS_ACL_SID_ENTRY_FK FOREIGN KEY (SID) REFERENCES EMS_ACL_SID (ID) 
);

ALTER TABLE EMS_REDIR_PETICIO ADD(
	CONSTRAINT EMS_REDIR_PETICIO_PK PRIMARY KEY (ID)
);

ALTER TABLE EMS_REDIR_MISSATGE ADD(
	CONSTRAINT EMS_REDIR_MISSATGE_PK PRIMARY KEY (ID),
	CONSTRAINT EMS_REDIR_PETICIO_MSG_FK FOREIGN KEY (PETICIO_ID) REFERENCES EMS_REDIR_PETICIO (ID) 
);

ALTER TABLE EMS_REDIR_SOLICITUD ADD(
	CONSTRAINT EMS_REDIR_SOLICITUD_PK PRIMARY KEY (ID),
	CONSTRAINT EMS_REDIR_PETICIO_SOLICIT_FK FOREIGN KEY (PETICIO_ID) REFERENCES EMS_REDIR_PETICIO (ID) 
);

ALTER TABLE EMS_USUARI ADD(
	CONSTRAINT EMS_USUARI_CODI_PK PRIMARY KEY (CODI), 
	CONSTRAINT EMS_USUARI_NIV_UK UNIQUE (NIF)
);

ALTER TABLE EMS_SERVEI ADD(
	CONSTRAINT EMS_SERVEI_ID_PK PRIMARY KEY (ID), 
	CONSTRAINT EMS_SERVEI_CODI_UK UNIQUE (CODI), 
	CONSTRAINT EMS_USUCRE_SERVEI_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES EMS_USUARI (CODI) , 
	CONSTRAINT EMS_USUMOD_SERVEI_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES EMS_USUARI (CODI) 
);

ALTER TABLE EMS_SERVEI_RUTA_DESTI ADD(
	CONSTRAINT EMS_SERVEI_RUTA_DESTI_PK PRIMARY KEY (ID),
	CONSTRAINT EMS_SERVEI_RUTA_FK FOREIGN KEY (SERVEI_ID) REFERENCES EMS_SERVEI (ID) , 
	CONSTRAINT EMS_USUCRE_SERRUT_FK FOREIGN KEY (CREATEDBY_CODI) REFERENCES EMS_USUARI (CODI) , 
	CONSTRAINT EMS_USUMOD_SERRUT_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) REFERENCES EMS_USUARI (CODI) 
);

ALTER TABLE schema_version ADD(
	CONSTRAINT schema_version_pk PRIMARY KEY (installed_rank)
);

ALTER TABLE EMS_BACKOFFICE_PET ADD CONSTRAINT EMS_BACKOFFICE_PET_PK PRIMARY KEY (ID);
ALTER TABLE EMS_BACKOFFICE_PET ADD CONSTRAINT EMS_SCSPPET_BACKPET_FK FOREIGN KEY (PETICIO_ID) REFERENCES CORE_PETICION_RESPUESTA (IDPETICION);


ALTER TABLE EMS_BACKOFFICE_SOL ADD CONSTRAINT EMS_BACKOFFICE_SOL_PK PRIMARY KEY (ID);
ALTER TABLE EMS_BACKOFFICE_SOL ADD CONSTRAINT EMS_BACKPET_BACKSOL_FK FOREIGN KEY (PETICIO_ID) REFERENCES EMS_BACKOFFICE_PET (ID);


ALTER TABLE EMS_BACKOFFICE_COM ADD CONSTRAINT EMS_BACKOFFICE_COM_PK PRIMARY KEY (ID);
ALTER TABLE EMS_BACKOFFICE_COM ADD CONSTRAINT EMS_BACKPET_BACKCOM_FK FOREIGN KEY (PETICIO_ID) REFERENCES EMS_BACKOFFICE_PET (ID);

ALTER TABLE EMS_BACKOFFICE_COM ADD CONSTRAINT EMS_BACKSOL_BACKCOM_FK FOREIGN KEY (SOLICITUD_ID) REFERENCES EMS_BACKOFFICE_SOL (ID);


ALTER TABLE EMS_BACKOFFICE_SOL ADD CONSTRAINT EMS_BACKCOM_BACKSOL_FK FOREIGN KEY (COMUNICACIO_ID) REFERENCES EMS_BACKOFFICE_COM (ID);

ALTER TABLE EMS_BACKOFFICE_PET ADD CONSTRAINT EMS_BACKCOM_BACKPET_FK FOREIGN KEY (COMUNICACIO_ID) REFERENCES EMS_BACKOFFICE_COM (ID);
