CREATE TABLE EMS_SERVEI_RUTA_DESTI
(
  ID                   NUMBER(19)               NOT NULL,
  ENTITAT_CODI         VARCHAR2(256)            NOT NULL,
  URL                  VARCHAR2(1024)           NOT NULL,
  SERVEI_ID            NUMBER(19)               NOT NULL,
  VERSION              NUMBER(19)               NOT NULL,
  CREATEDDATE          TIMESTAMP(6),
  LASTMODIFIEDDATE     TIMESTAMP(6),
  CREATEDBY_CODI       VARCHAR2(256),
  LASTMODIFIEDBY_CODI  VARCHAR2(256)
);

ALTER TABLE EMS_SERVEI_RUTA_DESTI ADD (
  PRIMARY KEY (ID));

ALTER TABLE EMS_SERVEI_RUTA_DESTI ADD (
  CONSTRAINT EMS_SERVEI_RUTA_FK FOREIGN KEY (SERVEI_ID) 
    REFERENCES EMS_SERVEI (ID),
  CONSTRAINT EMS_USUCRE_SERRUT_FK FOREIGN KEY (CREATEDBY_CODI) 
    REFERENCES EMS_USUARI (CODI),
  CONSTRAINT EMS_USUMOD_SERRUT_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) 
    REFERENCES EMS_USUARI (CODI));

GRANT SELECT, UPDATE, INSERT, DELETE ON EMS_SERVEI_RUTA_DESTI TO WWW_EMISERV;

ALTER TABLE EMS_SERVEI ADD COLUMN TIPUS NUMBER(2);
UPDATE EMS_SERVEI SET TIPUS = 0;
ALTER TABLE EMS_SERVEI ADD COLUMN TIPUS NOT NULL;
ALTER TABLE EMS_SERVEI ADD COLUMN RESOLVER_CLASS VARCHAR2(1024);
ALTER TABLE EMS_SERVEI MODIFY (BACKOFFICE_CLASS NULL);
ALTER TABLE EMS_SERVEI ADD COLUMN URL_PER_DEFECTE VARCHAR2(256);

CREATE TABLE EMS_REDIR_PETICIO
(
  ID                 NUMBER(19)                 NOT NULL,
  DATA_COMPROVACIO   TIMESTAMP(6),
  DATA_PETICIO       TIMESTAMP(6),
  DATA_RESPOSTA      TIMESTAMP(6),
  ERROR              CLOB,
  ESTAT              VARCHAR2(64)               NOT NULL,
  NUM_ENVIAMENTS     NUMBER(10)                 NOT NULL,
  NUM_TRANSMISSIONS  NUMBER(10)                 NOT NULL,
  PETICIO_ID         VARCHAR2(512)              NOT NULL,
  SERVEI_CODI        VARCHAR2(1024)             NOT NULL,
  SINCRONA           NUMBER(1),
  TER                TIMESTAMP(6),
  VERSION            NUMBER(19)                 NOT NULL
);
ALTER TABLE EMS_REDIR_PETICIO ADD (
  PRIMARY KEY (ID));

CREATE TABLE EMS_REDIR_SOLICITUD
(
  ID                  NUMBER(19)                NOT NULL,
  CONSENTIMENT        VARCHAR2(12),
  DATA_GENERACIO      TIMESTAMP(6),
  ERROR               CLOB,
  ESTAT               VARCHAR2(16),
  FINALITAT           VARCHAR2(1024),
  FUNCIONARI_DOC      VARCHAR2(64),
  FUNCIONARI_NOM      VARCHAR2(640),
  PROCEDIMENT_CODI    VARCHAR2(1024),
  PROCEDIMENT_NOM     VARCHAR2(1024),
  SOLICITANT_ID       VARCHAR2(160)             NOT NULL,
  SOLICITANT_NOM      VARCHAR2(1024),
  SOLICITUD_ID        VARCHAR2(1024)            NOT NULL,
  TITULAR_DOC         VARCHAR2(64),
  TITULAR_LLINATGE1   VARCHAR2(640),
  TITULAR_LLINATGE2   VARCHAR2(640),
  TITULAR_NOM         VARCHAR2(640),
  TITULAR_NOM_SENCER  VARCHAR2(1024),
  TRANSMISION_ID      VARCHAR2(1024),
  UNITAT_TRAMITADORA  VARCHAR2(1024),
  VERSION             NUMBER(19)                NOT NULL,
  PETICIO_ID          NUMBER(19)                NOT NULL
);
ALTER TABLE EMS_REDIR_SOLICITUD ADD (
  PRIMARY KEY (ID));
ALTER TABLE EMS_REDIR_SOLICITUD ADD (
  CONSTRAINT EMS_REDIR_PETICIO_SOLICIT_FK FOREIGN KEY (PETICIO_ID) 
    REFERENCES EMS_REDIR_PETICIO (ID));

CREATE TABLE EMS_REDIR_MISSATGE
(
  ID          NUMBER(19)                        NOT NULL,
  TIPUS       NUMBER(10)                        NOT NULL,
  VERSION     NUMBER(19)                        NOT NULL,
  XML         CLOB,
  PETICIO_ID  NUMBER(19)                        NOT NULL
);
ALTER TABLE EMS_REDIR_MISSATGE ADD (
  PRIMARY KEY (ID));
ALTER TABLE EMS_REDIR_MISSATGE ADD (
  CONSTRAINT EMS_REDIR_PETICIO_MSG_FK FOREIGN KEY (PETICIO_ID) 
    REFERENCES EMS_REDIR_PETICIO (ID));

ALTER TABLE EMS_SERVEI RENAME COLUMN BACKCAIB_AUTENTICAT TO BACKCAIB_AUTENTICACIO;
ALTER TABLE EMS_SERVEI MODIFY BACKCAIB_AUTENTICACIO NUMBER(10);

-- Millora. Servei de família nombrosa 11/2016
ALTER TABLE EMS_SERVEI ADD COLUMN RESPONSE_RESOLVER_CLASS VARCHAR2(1024);
ALTER TABLE EMS_SERVEI_RUTA_DESTI ADD COLUMN ORDRE NUMBER(19);

-- Millora peticions asíncrones
CREATE TABLE EMS_BACKOFFICE_COM
(
  ID            NUMBER(19)                      NOT NULL,
  PETICIO_ID    NUMBER(19)                      NOT NULL,
  SOLICITUD_ID  NUMBER(19),
  PETICIO_DATA  TIMESTAMP(6)                    NOT NULL,
  PETICIO_XML   CLOB                            NOT NULL,
  RESPOSTA_DATA TIMESTAMP (6),
  RESPOSTA_XML  CLOB,
  VERSION       NUMBER(19)
);

CREATE TABLE EMS_BACKOFFICE_PET
(
  ID                NUMBER(19)                  NOT NULL,
  PETICIO_ID        VARCHAR2(26)                NOT NULL,
  ESTAT             NUMBER(10)                  NOT NULL,
  TER_DATA          TIMESTAMP (6)               NOT NULL,
  DARRERA_SOL_DATA  TIMESTAMP (6),
  DARRERA_SOL_ID    VARCHAR2(256),
  PROCESSADES_ERROR NUMBER(10),
  PROCESSADES_TOTAL NUMBER(10),
  COMUNICACIO_ID    NUMBER(19),
  VERSION           NUMBER(19)
);

CREATE TABLE EMS_BACKOFFICE_SOL
(
  ID             NUMBER(19)                     NOT NULL,
  PETICIO_ID     NUMBER(19)                     NOT NULL,
  SOLICITUD_ID   VARCHAR2(256)                  NOT NULL,
  ESTAT          NUMBER(10)                     NOT NULL,
  COMUNICACIO_ID NUMBER(19),
  VERSION        NUMBER(19)
);

ALTER TABLE EMS_BACKOFFICE_COM ADD (
  PRIMARY KEY (ID));

ALTER TABLE EMS_BACKOFFICE_PET ADD (
  PRIMARY KEY (ID));

ALTER TABLE EMS_BACKOFFICE_SOL ADD (
  PRIMARY KEY (ID));

ALTER TABLE EMS_BACKOFFICE_COM ADD (
  CONSTRAINT EMS_BACKPET_BACKCOM_FK FOREIGN KEY (PETICIO_ID) 
    REFERENCES EMS_BACKOFFICE_PET (ID),
  CONSTRAINT EMS_BACKSOL_BACKCOM_FK FOREIGN KEY (SOLICITUD_ID) 
    REFERENCES EMS_BACKOFFICE_SOL (ID));

ALTER TABLE EMS_BACKOFFICE_PET ADD (
  CONSTRAINT EMS_SCSPPET_BACKPET_FK FOREIGN KEY (PETICIO_ID) 
    REFERENCES CORE_PETICION_RESPUESTA (IDPETICION),
  CONSTRAINT EMS_BACKCOM_BACKPET_FK FOREIGN KEY (COMUNICACIO_ID) 
    REFERENCES EMS_BACKOFFICE_COM (ID));

ALTER TABLE EMS_BACKOFFICE_SOL ADD (
  CONSTRAINT EMS_BACKPET_BACKSOL_FK FOREIGN KEY (PETICIO_ID) 
    REFERENCES EMS_BACKOFFICE_PET (ID),
  CONSTRAINT EMS_BACKCOM_BACKSOL_FK FOREIGN KEY (COMUNICACIO_ID) 
    REFERENCES EMS_BACKOFFICE_COM (ID));

ALTER TABLE EMS_SERVEI ADD COLUMN BACKCAIB_ASYNC_TIPUS NUMBER(10);
ALTER TABLE EMS_SERVEI ADD COLUMN BACKCAIB_ASYNC_TER NUMBER(10);
UPDATE EMS_SERVEI SET BACKCAIB_ASYNC_TER = 0;

-- Millora informe estat general v.1.3.22 02/2017
-- afegir camp emisor a la taula de peticions
ALTER TABLE EMS_REDIR_PETICIO ADD EMISSOR_CODI VARCHAR2(10);
