GRANT SELECT, UPDATE, INSERT, DELETE ON SCSP_CODIGO_ERROR TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_TRANSMISION TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_TIPO_MENSAJE TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_CACHE_CERTIFICADOS TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON SCSP_ESTADO_PETICION TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_MODULO TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_MODULO_CONFIGURACION TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_CLAVE_PUBLICA TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_SECUENCIA_IDPETICION TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_PETICION_RESPUESTA TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_TOKEN_DATA TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_PARAMETRO_CONFIGURACION TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_EMISOR_CERTIFICADO TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_SERVICIO TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON ORGANISMO_CESIONARIO TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_CLAVE_PRIVADA TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_LOG TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON AUTORIZACION_APLICACION TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON AUTORIZACION_CA TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON AUTORIZACION_CERTIFICADO TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON AUTORIZACION_ORGANISMO TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON EMISOR_BACKOFFICE TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON SCSP_SECUENCIA_IDTRANSMISION TO WWW_EMISERV;
GRANT SELECT, UPDATE, INSERT, DELETE ON SCSP_CODIGO_ERROR_SECUNDARIO TO WWW_EMISERV;

GRANT EXECUTE ON GETSECUENCIAIDTRANSMISION TO WWW_EMISERV;

GRANT SELECT ON ID_LOG_SEQUENCE TO WWW_EMISERV;
