create table core_emisor_certificado (id bigint not null, cif varchar(512) not null, fechabaja date not null, nombre varchar(64) not null, primary key (id))
create table core_peticion_respuesta (idpeticion varchar(26) not null, certificado bigint, error varchar(256), estado varchar(4), ter timestamp, fechapeticion timestamp not null, fecharespuesta timestamp, fechaultimosondeo timestamp, numeroenvios integer, numerotransmisiones integer, transmisionsincrona boolean, primary key (idpeticion))
create table core_servicio (id bigint not null, actionasincrona varchar(256), actionsincrona varchar(256), actionsolicitud varchar(256), algoritmocifrado varchar(32), caducidad integer, clavecifrado bigint, clavefirma bigint, codcertificado varchar(64) not null, descripcion varchar(512) not null, esquemas varchar(256), fechaalta date not null, fechabaja date not null, maxsolicitudespeticion integer, numeromaximoreenvios integer, prefijoidtransmision varchar(8), prefijopeticion varchar(8), timeout integer, tiposeguridad varchar(16), urlasincrona varchar(256), urlsincrona varchar(256), validacionfirma varchar(32), versionesquema varchar(32), xpathcifradoasincrono varchar(256), xpathcifradosincrono varchar(256), xpathcodigoerror varchar(256), xpathliteralerror varchar(256), emisor bigint not null, primary key (id))
create table core_token_data (idpeticion varchar(26) not null, datos longvarchar, tipomensaje integer not null, primary key (idpeticion, tipomensaje))
create table core_transmision (idpeticion varchar(26) not null, consentimiento varchar(256), error varchar(256), estado varchar(256), expediente varchar(256), fechageneracion timestamp not null, finalidad varchar(256), docfuncionario varchar(16), nombrefuncionario varchar(128), codigoprocedimiento varchar(256), nombreprocedimiento varchar(256), idsolicitante varchar(10) not null, nombresolicitante varchar(256), idsolicitud varchar(64) not null, apellido1titular varchar(40), apellido2titular varchar(40), doctitular varchar(16), nombretitular varchar(40), nombrecompletotitular varchar(40), idtransmision varchar(64), unidadtramitadora varchar(256), xmltransmision varchar(256), primary key (idpeticion))
create table emisor_backoffice (certificado bigint not null, beanname varchar(256), classname varchar(256), ter integer not null, primary key (certificado))
create table ems_backoffice_com (id bigint generated by default as identity (start with 1), error clob(255), peticio_data timestamp not null, peticio_xml clob(255) not null, resposta_data timestamp, resposta_xml clob(255), version bigint not null, peticio_id bigint not null, solicitud_id bigint, primary key (id))
create table ems_backoffice_pet (id bigint generated by default as identity (start with 1), darrera_sol_data timestamp, darrera_sol_id varchar(256), estat integer not null, processades_error integer, processades_total integer, ter_data timestamp not null, version bigint not null, comunicacio_id bigint, peticio_id varchar(26) not null, primary key (id))
create table ems_backoffice_sol (id bigint generated by default as identity (start with 1), estat integer, solicitud_id varchar(256), version bigint not null, comunicacio_id bigint, peticio_id bigint not null, primary key (id))
create table ems_redir_missatge (id bigint generated by default as identity (start with 1), tipus integer not null, version bigint not null, xml clob(255), peticio_id bigint not null, primary key (id))
create table ems_redir_peticio (id bigint generated by default as identity (start with 1), data_comprovacio timestamp, data_peticio timestamp, data_resposta timestamp, emissor_codi varchar(10), error clob(255), estat varchar(16) not null, num_enviaments integer not null, num_transmissions integer not null, peticio_id varchar(128) not null, servei_codi varchar(256) not null, sincrona boolean, ter timestamp, version bigint not null, primary key (id))
create table ems_redir_solicitud (id bigint generated by default as identity (start with 1), consentiment varchar(3), data_generacio timestamp, error clob(255), estat varchar(4), finalitat varchar(256), funcionari_doc varchar(16), funcionari_nom varchar(160), procediment_codi varchar(256), procediment_nom varchar(256), solicitant_id varchar(40) not null, solicitant_nom varchar(256), solicitud_id varchar(256) not null, titular_doc varchar(16), titular_llinatge1 varchar(160), titular_llinatge2 varchar(160), titular_nom varchar(160), titular_nom_sencer varchar(256), transmision_id varchar(256), unitat_tramitadora varchar(256), version bigint not null, peticio_id bigint not null, primary key (id))
create table ems_servei (id bigint generated by default as identity (start with 1), createdDate timestamp, lastModifiedDate timestamp, actiu boolean, backcaib_async_ter integer, backcaib_async_tipus integer, backcaib_autenticacio integer, backcaib_url varchar(256), backoffice_class varchar(256), codi varchar(64) not null, configurat boolean, descripcio varchar(1024), nom varchar(256) not null, resolver_class varchar(256), response_resolver_class varchar(256), tipus integer not null, url_per_defecte varchar(256), version bigint not null, createdBy_codi varchar(64), lastModifiedBy_codi varchar(64), primary key (id))
create table ems_servei_ruta_desti (id bigint generated by default as identity (start with 1), createdDate timestamp, lastModifiedDate timestamp, entitat_codi varchar(64) not null, ordre bigint, url varchar(256) not null, version bigint not null, createdBy_codi varchar(64), lastModifiedBy_codi varchar(64), servei_id bigint not null, primary key (id))
create table ems_usuari (codi varchar(64) not null, email varchar(200), inicialitzat boolean, nif varchar(9) not null, nom varchar(200), version bigint not null, primary key (codi))
alter table ems_servei add constraint UK_dlfa2xr11di4emmvnvabmq3cc unique (codi)
alter table ems_usuari add constraint UK_539b80tvgnx6ym2lygyuyywd1 unique (nif)
alter table core_peticion_respuesta add constraint FK_3u4oty74nqbb53ve2j6l28i54 foreign key (certificado) references core_servicio
alter table core_servicio add constraint FK_n63xam7whok9mityenwr6n7sj foreign key (emisor) references core_emisor_certificado
alter table core_transmision add constraint FK_4cvcukmh4d6v02rawt9du16a4 foreign key (idpeticion) references core_peticion_respuesta
alter table ems_backoffice_com add constraint ems_backpet_backcom_fk foreign key (peticio_id) references ems_backoffice_pet
alter table ems_backoffice_com add constraint ems_backsol_backcom_fk foreign key (solicitud_id) references ems_backoffice_sol
alter table ems_backoffice_pet add constraint ems_backcom_backpet_fk foreign key (comunicacio_id) references ems_backoffice_com
alter table ems_backoffice_pet add constraint ems_scsppet_backpet_fk foreign key (peticio_id) references core_peticion_respuesta
alter table ems_backoffice_sol add constraint ems_backcom_backsol_fk foreign key (comunicacio_id) references ems_backoffice_com
alter table ems_backoffice_sol add constraint ems_backpet_backsol_fk foreign key (peticio_id) references ems_backoffice_pet
alter table ems_redir_missatge add constraint ems_redir_peticio_msg_fk foreign key (peticio_id) references ems_redir_peticio
alter table ems_redir_solicitud add constraint ems_redir_peticio_solicit_fk foreign key (peticio_id) references ems_redir_peticio
alter table ems_servei add constraint FK_1htkm0dah2re29okwihcxo8p2 foreign key (createdBy_codi) references ems_usuari
alter table ems_servei add constraint FK_1j3b4hdgjf3kymabqux598pcx foreign key (lastModifiedBy_codi) references ems_usuari
alter table ems_servei_ruta_desti add constraint FK_6cij3lspoqdfg5ud7t3wvsspj foreign key (createdBy_codi) references ems_usuari
alter table ems_servei_ruta_desti add constraint FK_rfdtk4ool3c2lrxgctnef8xep foreign key (lastModifiedBy_codi) references ems_usuari
alter table ems_servei_ruta_desti add constraint ems_servei_ruta_fk foreign key (servei_id) references ems_servei
alter table ems_servei_ruta_desti add constraint FK_67lxsub46l91ep5su1m9fo4o1 foreign key (servei_id) references ems_redir_peticio
create sequence id_servicio_sequence start with 1
create table core_cache_certificados (autoridadcertif varchar(512) not null, numserie varchar(256) not null, revocado int default 0 not null, tiempocomprobacion timestamp not null, primary key (autoridadcertif, numserie))
create table core_clave_privada (id bigint generated by default as identity (start with 1), alias varchar(256) not null, fechaAlta timestamp, fechaBaja timestamp, interoperabilidad boolean not null, nombre varchar(256) not null, numeroSerie varchar(256) not null, password varchar(256) not null, organismo bigint, primary key (id))
create table core_clave_publica (id bigint generated by default as identity (start with 1), alias varchar(256) not null, fechaAlta timestamp, fechaBaja timestamp, nombre varchar(256) not null, numeroSerie varchar(256) not null, primary key (id))
create table core_codigo_error (codigo varchar(4) not null, descripcion varchar(1024) not null, primary key (codigo))
create table core_em_aplicacion (idAplicacion integer generated by default as identity (start with 1), cn varchar(512), fechaalta timestamp, fechabaja timestamp, nifCertificado varchar(16), numeroSerie varchar(64) not null, tiempoComprobacion timestamp, autoridadcertif varchar(512) not null, primary key (idAplicacion))
create table core_em_autorizacion_ca (codca varchar(512) not null, nombre varchar(256), primary key (codca))
create table core_em_autorizacion_cert (id bigint generated by default as identity (start with 1), fechaAlta timestamp, fechaBaja timestamp, idaplicacion integer not null, idorganismo bigint not null, idcertificado bigint not null, primary key (id))
create table core_em_autorizacion_organismo (id bigint generated by default as identity (start with 1), fechaAlta timestamp not null, fechaBaja timestamp, idorganismo varchar(16) not null, nombreOrganismo varchar(64), primary key (id))
create table core_em_backoffice (beanName varchar(256), className varchar(256), ter int default 24 not null, certificado bigint not null, primary key (certificado))
create table core_em_codigo_error_secun (codigosecundario varchar(4) not null, descripcion varchar(216), codigo varchar(4) not null, primary key (codigo, codigosecundario))
create table core_em_secuencia_idtrans (prefijo varchar(9) not null, fechaGeneracion timestamp not null, secuencia varchar(26) not null, primary key (prefijo))
create table core_estado_peticion (codigo varchar(4) not null, mensaje varchar(256) not null, primary key (codigo))
create table core_log (id bigint generated by default as identity (start with 1), clase varchar(256), criticidad varchar(10), fecha timestamp, mensaje clob(255), metodo varchar(64), primary key (id))
create table core_modulo (nombre varchar(256) not null, activoEntrada int default 1 not null, activoSalida int default 1 not null, descripcion varchar(512) not null, primary key (nombre))
create table core_modulo_configuracion (activoEntrada int default 1 not null, activoSalida int default 1 not null, modulo varchar(256) not null, certificado bigint not null, primary key (modulo, certificado))
create table core_organismo_cesionario (id bigint generated by default as identity (start with 1), bloqueado boolean not null, cif varchar(10) not null, fechaAlta timestamp not null, fechaBaja timestamp, logo blob(10485760), nombre varchar(50) not null, primary key (id))
create table core_parametro_configuracion (nombre varchar(64) not null, descripcion varchar(512), valor varchar(512) not null, primary key (nombre))
alter table core_peticion_respuesta add column descompuesta varchar(1)
create table core_req_modulo_pdf (nombre varchar(256) not null, activo int default 1 not null, orden integer not null, primary key (nombre))
create table core_req_modulo_pdf_cesionario (activo int default 1 not null, modulo varchar(256) not null, organismo bigint not null, servicio bigint not null, primary key (modulo, organismo, servicio))
alter table core_servicio add column plantillaXSLT varchar(512)
create table core_tipo_mensaje (tipo integer not null, descripcion varchar(32) not null, primary key (tipo))
alter table core_token_data add column algoritmoEncriptacion varchar(32)
alter table core_token_data add column clave varchar(256)
alter table core_token_data add column modoEncriptacion varchar(32)
alter table core_em_autorizacion_cert add constraint unique_serv_apl_org_baja unique (idcertificado, idorganismo, idaplicacion, fechaBaja)
create index core_transmision_index_idpet on core_transmision (idpeticion)
alter table core_clave_privada add constraint clavePrivada_Organismo foreign key (organismo) references core_organismo_cesionario
alter table core_em_aplicacion add constraint apli_codca foreign key (autoridadcertif) references core_em_autorizacion_ca
alter table core_em_autorizacion_cert add constraint aut_cert_aplicacion foreign key (idaplicacion) references core_em_aplicacion
alter table core_em_autorizacion_cert add constraint aut_cert_organismo foreign key (idorganismo) references core_em_autorizacion_organismo
alter table core_em_autorizacion_cert add constraint aut_cert_servicio foreign key (idcertificado) references core_servicio
alter table core_em_backoffice add constraint emisor_bo_servicio foreign key (certificado) references core_servicio
alter table core_em_codigo_error_secun add constraint codigosecundario_fk foreign key (codigo) references core_codigo_error
alter table core_modulo_configuracion add constraint mod_conf_modulo foreign key (modulo) references core_modulo
alter table core_modulo_configuracion add constraint mod_conf_servicio foreign key (certificado) references core_servicio
alter table core_req_modulo_pdf_cesionario add constraint fk_modulo_mod_pdf foreign key (modulo) references core_req_modulo_pdf
alter table core_req_modulo_pdf_cesionario add constraint fk_org_cesionario_mod_pdf foreign key (organismo) references core_organismo_cesionario
alter table core_req_modulo_pdf_cesionario add constraint fk_servicio_mod_pdf foreign key (servicio) references core_servicio
alter table core_servicio add constraint serv_clavecifrado foreign key (clavecifrado) references core_clave_publica
alter table core_servicio add constraint serv_clavefirma foreign key (clavefirma) references core_clave_privada
alter table core_token_data add constraint toke_tipo foreign key (tipomensaje) references core_tipo_mensaje
alter table core_token_data add constraint token_peticion foreign key (idpeticion) references core_peticion_respuesta
create table core_req_cesionarios_servicios (id bigint generated by default as identity (start with 1), bloqueado boolean not null, fechaAlta timestamp not null, fechaBaja timestamp, claveprivada bigint, organismo bigint, servicio bigint, primary key (id))
create table core_req_secuencia_idpeticion (prefijo varchar(9) not null, fechaGeneracion timestamp not null, secuencia varchar(23) not null, primary key (prefijo))

CREATE TABLE EMS_ACL_SID(ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,PRINCIPAL BIT(1) NOT NULL,SID VARCHAR(100) NOT NULL)
ALTER TABLE EMS_ACL_SID ALTER COLUMN ID RESTART WITH 3
CREATE TABLE EMS_ACL_CLASS(ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 100) NOT NULL PRIMARY KEY,CLASS VARCHAR(100) COLLATE SQL_TEXT_UCC NOT NULL,CONSTRAINT UNIQUE_UK_2 UNIQUE(CLASS))
ALTER TABLE EMS_ACL_CLASS ALTER COLUMN ID RESTART WITH 1
CREATE TABLE EMS_ACL_OBJECT_IDENTITY(ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 100) NOT NULL PRIMARY KEY,OBJECT_ID_CLASS BIGINT NOT NULL,OBJECT_ID_IDENTITY BIGINT NOT NULL,PARENT_OBJECT BIGINT,OWNER_SID BIGINT,ENTRIES_INHERITING BOOLEAN NOT NULL,CONSTRAINT UNIQUE_UK_3 UNIQUE(OBJECT_ID_CLASS,OBJECT_ID_IDENTITY),CONSTRAINT FOREIGN_FK_1 FOREIGN KEY(PARENT_OBJECT) REFERENCES EMS_ACL_OBJECT_IDENTITY(ID),CONSTRAINT FOREIGN_FK_2 FOREIGN KEY(OBJECT_ID_CLASS) REFERENCES EMS_ACL_CLASS(ID),CONSTRAINT FOREIGN_FK_3 FOREIGN KEY(OWNER_SID) REFERENCES EMS_ACL_SID(ID))
ALTER TABLE EMS_ACL_OBJECT_IDENTITY ALTER COLUMN ID RESTART WITH 1
CREATE TABLE EMS_ACL_ENTRY(ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 100) NOT NULL PRIMARY KEY,ACL_OBJECT_IDENTITY BIGINT NOT NULL,ACE_ORDER INTEGER NOT NULL,SID BIGINT NOT NULL,MASK INTEGER NOT NULL,GRANTING BOOLEAN NOT NULL,AUDIT_SUCCESS BOOLEAN NOT NULL,AUDIT_FAILURE BOOLEAN NOT NULL,CONSTRAINT UNIQUE_UK_4 UNIQUE(ACL_OBJECT_IDENTITY,ACE_ORDER),CONSTRAINT FOREIGN_FK_4 FOREIGN KEY(ACL_OBJECT_IDENTITY) REFERENCES EMS_ACL_OBJECT_IDENTITY(ID),CONSTRAINT FOREIGN_FK_5 FOREIGN KEY(SID) REFERENCES EMS_ACL_SID(ID))
ALTER TABLE EMS_ACL_ENTRY ALTER COLUMN ID RESTART WITH 1

insert into core_codigo_error (codigo,descripcion) values ('0101','Error al contactar con el servicio Web especificado {0} {1}')
insert into core_codigo_error (codigo,descripcion) values ('0102','Comunicación sin respuesta {0} {1}')
insert into core_codigo_error (codigo,descripcion) values ('0103','Servidor responde mensaje que no es XML')
insert into core_codigo_error (codigo,descripcion) values ('0201','Error al generar el identificativo de petición')
insert into core_codigo_error (codigo,descripcion) values ('0202','Error al insertar la petición {0}')
insert into core_codigo_error (codigo,descripcion) values ('0203','Error al actualizar el estado {0} {1}')
insert into core_codigo_error (codigo,descripcion) values ('0204','Error al actualizar el TER {0} {1}')
insert into core_codigo_error (codigo,descripcion) values ('0205','Error al actualizar la fecha de último sondeo {0} {1}')
insert into core_codigo_error (codigo,descripcion) values ('0206','Error al actualizar el fichero de respuesta {0}')
insert into core_codigo_error (codigo,descripcion) values ('0207','Error al recuperar el estado de la petición {0}')
insert into core_codigo_error (codigo,descripcion) values ('0208','Fichero de respuesta caducado {0}')
insert into core_codigo_error (codigo,descripcion) values ('0209','Error al comprobar las transmisiones insertadas {0}')
insert into core_codigo_error (codigo,descripcion) values ('0210','Error al recuperar el CIF del Organismo Requirente {0}')
insert into core_codigo_error (codigo,descripcion) values ('0211','Error al recuperar el TER {0}')
insert into core_codigo_error (codigo,descripcion) values ('0212','Error al descomponer el fichero de petición {0}')
insert into core_codigo_error (codigo,descripcion) values ('0213','Error al recuperar peticiones pendientes. {0}')
insert into core_codigo_error (codigo,descripcion) values ('0214','Error al insertar las transmisiones. {0}')
insert into core_codigo_error (codigo,descripcion) values ('0215','Error al actualizar el campo error {0} {1}')
insert into core_codigo_error (codigo,descripcion) values ('0216','Error al actualizar el mensaje de respuesta {0}')
insert into core_codigo_error (codigo,descripcion) values ('0217','Error al recuperar la CADUCIDAD {0}')
insert into core_codigo_error (codigo,descripcion) values ('0218','Error al descomponer el mensaje de petición {0}')
insert into core_codigo_error (codigo,descripcion) values ('0219','Error al recuperar el fichero de respuesta {0}')
insert into core_codigo_error (codigo,descripcion) values ('0220','Error al enviar la alarma de la petición {0}')
insert into core_codigo_error (codigo,descripcion) values ('0221','Error al comprobar las peticiones pendientes.')
insert into core_codigo_error (codigo,descripcion) values ('0222','Error al borrar las respuestas caducadas.')
insert into core_codigo_error (codigo,descripcion) values ('0223','Error al escribir el fichero de errores {0}')
insert into core_codigo_error (codigo,descripcion) values ('0224','Error al borrar el fichero de error {0}')
insert into core_codigo_error (codigo,descripcion) values ('0225','Se ha alcanzado el número máximo de respuestas para la petición servidas.{0}')
insert into core_codigo_error (codigo,descripcion) values ('0226','Error al parsear el XML {0}')
insert into core_codigo_error (codigo,descripcion) values ('0227','Error al generar la respuesta. {0}')
insert into core_codigo_error (codigo,descripcion) values ('0229','La petición ya ha sido tramitada o ya existe en el sistema, está repetida')
insert into core_codigo_error (codigo,descripcion) values ('0230','El timestamp de la petición debe ser válido y de hoy o de ayer. {0}')
insert into core_codigo_error (codigo,descripcion) values ('0231','Documento Incorrecto {0}')
insert into core_codigo_error (codigo,descripcion) values ('0232','Documento con más de un identificador.{0}')
insert into core_codigo_error (codigo,descripcion) values ('0233','Titular no identificado.')
insert into core_codigo_error (codigo,descripcion) values ('0234','{0}. No se ha encontrado en base de datos configuración alguna para algún certificado asociado al código pasado por parámetro.')
insert into core_codigo_error (codigo,descripcion) values ('0235','El NIF del certificado no coincide con el tag NifSolicitante.')
insert into core_codigo_error (codigo,descripcion) values ('0236','Consentimiento del solicitante inválido. {0}')
insert into core_codigo_error (codigo,descripcion) values ('0237','Tag NumElementos inválido. {0}')
insert into core_codigo_error (codigo,descripcion) values ('0238','Información no disponible.')
insert into core_codigo_error (codigo,descripcion) values ('0239','Error al tratar los datos específicos. {0}')
insert into core_codigo_error (codigo,descripcion) values ('0240','Formato de documento inválido para NIE')
insert into core_codigo_error (codigo,descripcion) values ('0241','Certificado o Respuesta Caducada')
insert into core_codigo_error (codigo,descripcion) values ('0242','Error genérico del BackOffice')
insert into core_codigo_error (codigo,descripcion) values ('0243','No todas las solicitudes de transmisión hacen referencia al mismo certificado especificado en nodo <Atributos>')
insert into core_codigo_error (codigo,descripcion) values ('0246','Error con los id transmision asignados por el backoffice. O todas las transmisiones poseen identificador o ninguna.{0}')
insert into core_codigo_error (codigo,descripcion) values ('0247','Error Tag TER no valido')
insert into core_codigo_error (codigo,descripcion) values ('0248','Error respuesta con un numero de transmisiones diferente a las solicitudes incluidas en la petición {0}')
insert into core_codigo_error (codigo,descripcion) values ('0301','Organismo no autorizado {0} {1}')
insert into core_codigo_error (codigo,descripcion) values ('0302','Certificado caducado {0}')
insert into core_codigo_error (codigo,descripcion) values ('0303','Certificado revocado {0}')
insert into core_codigo_error (codigo,descripcion) values ('0304','El DN del Organismo Requirente no coincide con el almacenado para la petición {0}')
insert into core_codigo_error (codigo,descripcion) values ('0305','Firma no válida {0}')
insert into core_codigo_error (codigo,descripcion) values ('0306','Error al generar la firma del mensaje {0}')
insert into core_codigo_error (codigo,descripcion) values ('0307','No se ha encontrado el nodo firma.')
insert into core_codigo_error (codigo,descripcion) values ('0308','Error al obtener la firma del mensaje SOAP {0}')
insert into core_codigo_error (codigo,descripcion) values ('0309','Error general al verificar el certificado :{0}')
insert into core_codigo_error (codigo,descripcion) values ('0310','No se ha podido verificar la CA del certificado.{0}')
insert into core_codigo_error (codigo,descripcion) values ('0311','No se ha encontrado el certificado firmante en el documento XML.{0}')
insert into core_codigo_error (codigo,descripcion) values ('0312','NIF del emisor especificado no coincide con el Organismo Emisor')
insert into core_codigo_error (codigo,descripcion) values ('0313','Error al Cifrar o descifrar el mensaje')
insert into core_codigo_error (codigo,descripcion) values ('0401','La estructura del fichero recibido no corresponde con el esquema.{0}')
insert into core_codigo_error (codigo,descripcion) values ('0402','Falta informar campo obligatorio {0} {1}')
insert into core_codigo_error (codigo,descripcion) values ('0403','Imposible obtener el contenido XML del mensaje SOAP.{0}')
insert into core_codigo_error (codigo,descripcion) values ('0404','Tipo de documento del titular inválido.')
insert into core_codigo_error (codigo,descripcion) values ('0405','Error al transformar el XML en texto plano a partir de la plantilla {0}.')
insert into core_codigo_error (codigo,descripcion) values ('0406','Contenido del mensaje SOAP no esperado')
insert into core_codigo_error (codigo,descripcion) values ('0501','Error de Base de Datos: {0}')
insert into core_codigo_error (codigo,descripcion) values ('0502','Error de sistema: {0}')
insert into core_codigo_error (codigo,descripcion) values ('0901','Servicio no disponible')
insert into core_codigo_error (codigo,descripcion) values ('0902','Modo síncrono no soportado.')
insert into core_codigo_error (codigo,descripcion) values ('0903','Modo asíncrono no soportado.')
insert into core_codigo_error (codigo,descripcion) values ('0904','Error general Indefinido {0}')
insert into core_codigo_error (codigo,descripcion) values ('0253','No todas las solicitudes tienen el mismo identificador de solicitante')
insert into core_codigo_error (codigo,descripcion) values ('0504','Error en la configuración {0}')
insert into core_codigo_error (codigo,descripcion) values ('0314','PROCEDIMIENTO {0} NO AUTORIZADO A CONSULTAR EL SERVICIO {1}')
insert into core_codigo_error (codigo,descripcion) values ('0244','CREAT PER JOSEPG')
insert into core_codigo_error (codigo,descripcion) values ('0414','El número de elementos no coincide con el número de solicitudes recibidas')
insert into core_codigo_error (codigo,descripcion) values ('0415','El número de solicitudes es mayor que 1, ejecute el servicio en modo asíncrono.')
insert into core_codigo_error (codigo,descripcion) values ('0419','Existen identificadores de solicitud repetidos.')

insert into core_parametro_configuracion (nombre, valor, descripcion) values ('keystoreType', 'jks', '')
insert into core_parametro_configuracion (nombre, valor, descripcion) values ('keystoreFile', 'file:/home/LIMIT_CECOMASA.LOCAL/josepg/Documents/Limit/config/keystores/interop_limit.jks', '')
insert into core_parametro_configuracion (nombre, valor, descripcion) values ('keystorePass', 'tecnologies', '')
insert into core_parametro_configuracion (nombre, valor, descripcion) values ('axis2.client.xml', '/axis2/axis2.xml', '')
insert into core_parametro_configuracion (nombre, valor, descripcion) values ('axis2.client.repository', '/axis2/', '')
insert into core_parametro_configuracion (nombre, valor, descripcion) values ('afirma.enabled', 'false', '')
insert into core_parametro_configuracion (nombre, valor, descripcion) values ('almacenamiento.ficheros', '/home/LIMIT_CECOMASA.LOCAL/josepg/Documents/Limit/webapp-data/emiserv/scsp/emisor/msg', '')
insert into core_parametro_configuracion (nombre, valor, descripcion) values ('almacenamiento.transmisiones', '1', '')
insert into core_modulo (nombre,descripcion,activoentrada,activosalida) values ('AlmacenarBaseDatos','AlmacenarBaseDatos','1','1')
insert into core_modulo (nombre,descripcion,activoentrada,activosalida) values ('ValidarCertificado','ValidarCertificado','0','0')
insert into core_modulo (nombre,descripcion,activoentrada,activosalida) values ('AlmacenarFichero','AlmacenarFichero','1','1')
insert into core_modulo (nombre,descripcion,activoentrada,activosalida) values ('ValidarEsquema','ValidarEsquema','0','0')
insert into core_modulo (nombre,descripcion,activoentrada,activosalida) values ('AlmacenarFicheroPlain','AlmacenarFicheroPlain','0','0')
insert into core_tipo_mensaje (tipo,descripcion) values ('0','Peticion')
insert into core_tipo_mensaje (tipo,descripcion) values ('1','ConfirmacionPeticion')
insert into core_tipo_mensaje (tipo,descripcion) values ('2','SolicitudRespuesta')
insert into core_tipo_mensaje (tipo,descripcion) values ('3','Respuesta')
insert into core_tipo_mensaje (tipo,descripcion) values ('4','Fault')

insert into core_emisor_certificado(id, cif, nombre, fechabaja) values (1, 'S2833002E', 'MINHAP', DATE '2099-12-31')
insert into core_emisor_certificado (id, cif, nombre, fechabaja) values (2, 'S0711001H', 'CAIB', DATE '2099-12-31')

insert into core_servicio (id,codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma) VALUES (1, 'SVDSCDWS01',NULL,'http://localhost:8380/emiserv/services/peticionAsincrona',NULL,'PeticionAsincrona','SolicitudRespuesta','V3','WS-Security','',NULL,NULL,'/schemas/SVDSCDWS01v3',NULL,NULL,'',50,999,NULL,'Comunicación de cambio de domicilio', 1,(SYSDATE),DATE '9999-12-31',10,'','',60,NULL)
insert into core_organismo_cesionario (id,nombre,cif,fechaalta,bloqueado) values (1,'MINHAP','S2833002E',DATE '2016-12-31',false)
insert into core_clave_privada (id,alias,fechaalta,interoperabilidad,nombre,password,numeroserie,organismo) values (1,'limit_pinbal_10anys',DATE '2016-12-31',false,'LIMIT TECNOLOGIES 10','tecnologies','1456745522','1')
insert into core_req_cesionarios_servicios (id,claveprivada,organismo,servicio,fechaAlta,bloqueado) values (1,1,1,1,DATE '2016-12-31',false)
--insert into core_peticion_respuesta (idpeticion,certificado,estado,fechapeticion,fecharespuesta,ter,numeroenvios,numerotransmisiones,fechaultimosondeo,transmisionsincrona,descompuesta) values ('SPP0000000121064',1,'0002',DATE '2016-12-31',null,null,'0','1',null,'1','N')
--insert into core_transmision (idsolicitud,idpeticion,idtransmision,idsolicitante,nombresolicitante,doctitular,docfuncionario,nombrefuncionario,fechageneracion,unidadtramitadora,codigoprocedimiento,nombreprocedimiento,expediente,finalidad,consentimiento,estado,nombretitular,apellido1titular,apellido2titular,nombrecompletotitular) values ('000001','SPP0000000121064','T250709511','B07167448','Limit Tecnologies','12345678Z','97669911C','Sion Andreu',DATE '2016-12-31',null,null,null,null,'ProvaConcepte#::##::#1234','Si',null,'Sion','Andreu',null,null)
--insert into core_token_data (idpeticion, tipomensaje, datos) values ('SPP0000000121064', '0', '<xml>')

insert into core_servicio (id,codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma) VALUES (2, 'SVDSCDDWS01','http://localhost:8380/emiserv/services/peticionSincrona','http://localhost:8380/emiserv/services/peticionAsincrona','PeticionSincrona','PeticionAsincrona','SolicitudRespuesta','V3','WS-Security','',NULL,NULL,'/schemas/SVDSCDDWS01v3',NULL,NULL,'',50,999,NULL,'Consulta de dades de discapacitat', 1,(SYSDATE),DATE '9999-12-31',10,'','',60,NULL)
insert into core_organismo_cesionario (id,nombre,cif,fechaalta,bloqueado) values (2,'Límit Tecnologies','B07167448',DATE '2016-12-31',false)
--insert into core_req_cesionarios_servicios (id,claveprivada,organismo,servicio,fechaAlta,bloqueado) values (1,1,2,2,DATE '2016-12-31',false)

insert into core_servicio (id,codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma) VALUES (3, 'EMISERVTEST','http://localhost:8380/emiserv/services/peticionSincrona','http://localhost:8380/emiserv/services/peticionAsincrona','PeticionSincrona','PeticionAsincrona','SolicitudRespuesta','V2','WS-Security','',NULL,NULL,'',NULL,NULL,'',50,999,NULL,'Proves EMISERV', 1,(SYSDATE),DATE '9999-12-31',10,'','',60,NULL)
--insert into core_req_cesionarios_servicios (id,claveprivada,organismo,servicio,fechaAlta,bloqueado) values (1,1,2,3,DATE '2016-12-31',false)
